import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Provider, Contract } from '../context'
import Body from '../Components/Body';
import NavigationBar from '../Components/NavigationBar';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <div className="App text">
      <Head>
        <title>Denarius</title>
        <meta name="viewport" content="width=device-width,initial-scale=1"></meta>
        <meta property="og:type" content="website"></meta>
        <meta property="og:url" content="  bvcn "></meta>
        <meta property="og:description" content="Denarius bla bla bla"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="Assets/favicon.png" />
      </Head>
      <Provider>
        <Contract>
          <NavigationBar></NavigationBar>
          <Body/>
          <Component {...pageProps} />
        </Contract>
      </Provider>
    </div>
  );
}

export default MyApp
